### PR TITLE
Recover decoder errors which are recoverable according to symphonia

### LINKED ISSUE #1: Symphonia decoder crashes for broken files
I am using the symphonia decoder with files that sometimes might be broken. If that is the case, the application panics due to this line:

https://github.com/10buttons/awedio/blob/58259816b4bad6503fdabfde9c475d878a466af8/src/sounds/decoders/symphonia.rs#L129

Before I open a PR to fix this problem: Was there a specific reason you didn't insert a `?` there? It seems at least that part of the code supported Result from the start. According to the symphonia docs, one should actually continue decoding the next packets if it is a DecodeError or IoError, which is what I want to implement.

BTW: Thanks for the nice crate! I used it to implement a hyper/tokio based backend which streams an audio stream as mp3 via HTTP. :)

### PR DESCRIPTION
**Pull request by jhbruhn**
This should fix #1 

The end of stream detection is still not very nice, but that's on symphonia

### CODE REVIEW

File: src/sounds/decoders/symphonia.rs [hunk 1]
```diff
@@ -125,8 +125,32 @@ impl SymphoniaDecoder {
...
+                Ok(buf_ref) => buf_ref,
+                // Recoverable, but this packet is void. Expect weird noises!
+                Err(Error::IoError(err)) => {
+                    if err.kind() == std::io::ErrorKind::UnexpectedEof
+                        && err.to_string() == "end of stream"
+                    {
+                        // According to Symphonia this is the only way to detect an end of stream
+                        return Err(Error::IoError(err));
+                    } else {
+                        log::warn!("IoError while decoding stream: {}", err);
```
Comment (benhansen-io) [inline src/sounds/decoders/symphonia.rs]: I am less confident that IoError should be skipped. Do you need them skipped for your project? If so do you have an example of an IoError that is skippable? If not I would prefer to still bubble these up as errors. Its always possible for the consumer to explicitly ignore IoErrors but wrapping a Sound in a Sound that calls next_sample if an IoError is returned but less flexible this way.

**Review by benhansen-io — COMMENTED** [review]
Thanks for the PR. One comment about IoError

File: src/sounds/decoders/symphonia.rs (hunk 1 above)
Comment (jhbruhn) [reply src/sounds/decoders/symphonia.rs]: I was also suprised, but it says so in the documentation [here](https://docs.rs/symphonia-core/latest/symphonia_core/codecs/trait.Decoder.html#tymethod.decode): "If a DecodeError or IoError is returned, the packet is undecodeable and should be discarded. Decoding may be continued with the next packet."

For my case, I can also live without this IoError special case, it is ugly anyways because of the ending-detection-logic. I am always decoding from RAM and thus shouldn't experience IoErrors.

**Review by benhansen-io — APPROVED** [review]
Great. Thanks!

**Comment by benhansen-io** [comment]
Sorry for the delay. I don't have many OSS projects and forgot I am supposed to do the merge. I'll put out a release later today.
